# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 700)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/icons/adjust-contrast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MainGrid = QtWidgets.QGridLayout()
        self.MainGrid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.MainGrid.setObjectName("MainGrid")
        self.StatusBox = QtWidgets.QGroupBox(self.centralwidget)
        self.StatusBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.StatusBox.setObjectName("StatusBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.StatusBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hlayout = QtWidgets.QHBoxLayout()
        self.hlayout.setContentsMargins(0, -1, 0, -1)
        self.hlayout.setObjectName("hlayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout.addItem(spacerItem)
        self.profile_btn = QtWidgets.QToolButton(self.StatusBox)
        self.profile_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.profile_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profile_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/man.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_btn.setIcon(icon1)
        self.profile_btn.setIconSize(QtCore.QSize(45, 45))
        self.profile_btn.setObjectName("profile_btn")
        self.hlayout.addWidget(self.profile_btn)
        self.notification_btn = QtWidgets.QToolButton(self.StatusBox)
        self.notification_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.notification_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notification_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/test/icons/bell-musical-tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notification_btn.setIcon(icon2)
        self.notification_btn.setIconSize(QtCore.QSize(45, 45))
        self.notification_btn.setObjectName("notification_btn")
        self.hlayout.addWidget(self.notification_btn)
        self.sync_btn = QtWidgets.QToolButton(self.StatusBox)
        self.sync_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.sync_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sync_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/test/icons/refresh-page-option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sync_btn.setIcon(icon3)
        self.sync_btn.setIconSize(QtCore.QSize(45, 45))
        self.sync_btn.setObjectName("sync_btn")
        self.hlayout.addWidget(self.sync_btn)
        self.preferrence_btn = QtWidgets.QToolButton(self.StatusBox)
        self.preferrence_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.preferrence_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.preferrence_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/test/icons/open-wrench-tool-silhouette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preferrence_btn.setIcon(icon4)
        self.preferrence_btn.setIconSize(QtCore.QSize(45, 45))
        self.preferrence_btn.setObjectName("preferrence_btn")
        self.hlayout.addWidget(self.preferrence_btn)
        self.log_off_btn = QtWidgets.QToolButton(self.StatusBox)
        self.log_off_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.log_off_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.log_off_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/test/icons/power-button-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_off_btn.setIcon(icon5)
        self.log_off_btn.setIconSize(QtCore.QSize(45, 45))
        self.log_off_btn.setObjectName("log_off_btn")
        self.hlayout.addWidget(self.log_off_btn)
        self.gridLayout_4.addLayout(self.hlayout, 0, 1, 1, 1)
        self.MainGrid.addWidget(self.StatusBox, 0, 0, 1, 1)
        self.ContentGrid = QtWidgets.QGridLayout()
        self.ContentGrid.setObjectName("ContentGrid")
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ContentGrid.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ContentGrid.addItem(spacerItem2, 0, 3, 1, 1)
        self.main_stackWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.main_stackWidget.setObjectName("main_stackWidget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.welcome_page)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btn_box = QtWidgets.QGroupBox(self.welcome_page)
        self.btn_box.setTitle("")
        self.btn_box.setObjectName("btn_box")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.btn_box)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 0, 0, 1, 1)
        self.project_stackWidget = QtWidgets.QStackedWidget(self.btn_box)
        self.project_stackWidget.setObjectName("project_stackWidget")
        self.btn_all_page = QtWidgets.QWidget()
        self.btn_all_page.setObjectName("btn_all_page")
        self.gridLayout = QtWidgets.QGridLayout(self.btn_all_page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 1, 1, 1)
        self.project_btn = QtWidgets.QPushButton(self.btn_all_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_btn.sizePolicy().hasHeightForWidth())
        self.project_btn.setSizePolicy(sizePolicy)
        self.project_btn.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.project_btn.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/test/icons/font-awesome_4-7-0_cube_256_0_000000_none.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.project_btn.setIcon(icon6)
        self.project_btn.setIconSize(QtCore.QSize(100, 100))
        self.project_btn.setObjectName("project_btn")
        self.gridLayout.addWidget(self.project_btn, 1, 1, 1, 1)
        self.econom_btn = QtWidgets.QPushButton(self.btn_all_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.econom_btn.sizePolicy().hasHeightForWidth())
        self.econom_btn.setSizePolicy(sizePolicy)
        self.econom_btn.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.econom_btn.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/test/icons/dollar-symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.econom_btn.setIcon(icon7)
        self.econom_btn.setIconSize(QtCore.QSize(100, 100))
        self.econom_btn.setObjectName("econom_btn")
        self.gridLayout.addWidget(self.econom_btn, 1, 3, 1, 1)
        self.member_btn = QtWidgets.QPushButton(self.btn_all_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.member_btn.sizePolicy().hasHeightForWidth())
        self.member_btn.setSizePolicy(sizePolicy)
        self.member_btn.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.member_btn.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/test/icons/group-profile-users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.member_btn.setIcon(icon8)
        self.member_btn.setIconSize(QtCore.QSize(100, 100))
        self.member_btn.setObjectName("member_btn")
        self.gridLayout.addWidget(self.member_btn, 3, 1, 1, 1)
        self.marketing_btn = QtWidgets.QPushButton(self.btn_all_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.marketing_btn.sizePolicy().hasHeightForWidth())
        self.marketing_btn.setSizePolicy(sizePolicy)
        self.marketing_btn.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.marketing_btn.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/test/icons/bull-horn-announcer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.marketing_btn.setIcon(icon9)
        self.marketing_btn.setIconSize(QtCore.QSize(100, 100))
        self.marketing_btn.setObjectName("marketing_btn")
        self.gridLayout.addWidget(self.marketing_btn, 3, 3, 1, 1)
        self.project_stackWidget.addWidget(self.btn_all_page)
        self.project_page = QtWidgets.QWidget()
        self.project_page.setObjectName("project_page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.project_page)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.project_page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 63, 16))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 541, 201))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.project_name_label = QtWidgets.QLabel(self.groupBox)
        self.project_name_label.setObjectName("project_name_label")
        self.horizontalLayout_4.addWidget(self.project_name_label)
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_4.addWidget(self.toolButton_4)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_4.addWidget(self.toolButton_3)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_5.addWidget(self.toolButton_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_5.addWidget(self.toolButton_5)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.toolButton_6 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_5.addWidget(self.toolButton_6)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_7 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_6.addWidget(self.toolButton_7)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.toolButton_8 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_6.addWidget(self.toolButton_8)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.toolButton_9 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_9.setObjectName("toolButton_9")
        self.horizontalLayout_6.addWidget(self.toolButton_9)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.toolButton_10 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_10.setObjectName("toolButton_10")
        self.horizontalLayout_7.addWidget(self.toolButton_10)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.toolButton_11 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_11.setObjectName("toolButton_11")
        self.horizontalLayout_7.addWidget(self.toolButton_11)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.toolButton_12 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_12.setObjectName("toolButton_12")
        self.horizontalLayout_7.addWidget(self.toolButton_12)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_8.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.project_stackWidget.addWidget(self.project_page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.project_stackWidget.addWidget(self.page_3)
        self.gridLayout_11.addWidget(self.project_stackWidget, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.btn_box, 0, 2, 1, 1)
        self.welcome_box = QtWidgets.QGroupBox(self.welcome_page)
        self.welcome_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.welcome_box.setTitle("")
        self.welcome_box.setObjectName("welcome_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.welcome_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.big_image_box = QtWidgets.QGroupBox(self.welcome_box)
        self.big_image_box.setMinimumSize(QtCore.QSize(280, 180))
        self.big_image_box.setMaximumSize(QtCore.QSize(300, 180))
        self.big_image_box.setTitle("")
        self.big_image_box.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.big_image_box.setObjectName("big_image_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.big_image_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.big_profile_btn = QtWidgets.QToolButton(self.big_image_box)
        self.big_profile_btn.setMinimumSize(QtCore.QSize(128, 128))
        self.big_profile_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.big_profile_btn.setText("")
        self.big_profile_btn.setIcon(icon1)
        self.big_profile_btn.setIconSize(QtCore.QSize(128, 128))
        self.big_profile_btn.setObjectName("big_profile_btn")
        self.gridLayout_5.addWidget(self.big_profile_btn, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.big_image_box)
        self.welcome_msg_box = QtWidgets.QGroupBox(self.welcome_box)
        self.welcome_msg_box.setMaximumSize(QtCore.QSize(16777215, 200))
        self.welcome_msg_box.setTitle("")
        self.welcome_msg_box.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.welcome_msg_box.setObjectName("welcome_msg_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.welcome_msg_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.welcome_label = QtWidgets.QLabel(self.welcome_msg_box)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        self.welcome_label.setFont(font)
        self.welcome_label.setScaledContents(True)
        self.welcome_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.welcome_label.setWordWrap(False)
        self.welcome_label.setObjectName("welcome_label")
        self.verticalLayout_2.addWidget(self.welcome_label)
        self.name_label = QtWidgets.QLabel(self.welcome_msg_box)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.name_label.setObjectName("name_label")
        self.verticalLayout_2.addWidget(self.name_label)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.welcome_msg_box)
        self.news_box = QtWidgets.QGroupBox(self.welcome_box)
        self.news_box.setTitle("")
        self.news_box.setObjectName("news_box")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.news_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame = QtWidgets.QFrame(self.news_box)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.news_frame_1 = QtWidgets.QFrame(self.frame)
        self.news_frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.news_frame_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.news_frame_1.setObjectName("news_frame_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.news_frame_1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recent_news_icon = QtWidgets.QToolButton(self.news_frame_1)
        self.recent_news_icon.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/test/icons/speech-bubbles-comment-option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recent_news_icon.setIcon(icon10)
        self.recent_news_icon.setIconSize(QtCore.QSize(20, 20))
        self.recent_news_icon.setObjectName("recent_news_icon")
        self.horizontalLayout.addWidget(self.recent_news_icon)
        self.news_label = QtWidgets.QLabel(self.news_frame_1)
        self.news_label.setObjectName("news_label")
        self.horizontalLayout.addWidget(self.news_label)
        self.verticalLayout_4.addWidget(self.news_frame_1)
        self.news_frame_2 = QtWidgets.QFrame(self.frame)
        self.news_frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.news_frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.news_frame_2.setObjectName("news_frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.news_frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.recent_news_icon_2 = QtWidgets.QToolButton(self.news_frame_2)
        self.recent_news_icon_2.setText("")
        self.recent_news_icon_2.setIcon(icon10)
        self.recent_news_icon_2.setIconSize(QtCore.QSize(20, 20))
        self.recent_news_icon_2.setObjectName("recent_news_icon_2")
        self.horizontalLayout_2.addWidget(self.recent_news_icon_2)
        self.news_label_2 = QtWidgets.QLabel(self.news_frame_2)
        self.news_label_2.setObjectName("news_label_2")
        self.horizontalLayout_2.addWidget(self.news_label_2)
        self.verticalLayout_4.addWidget(self.news_frame_2)
        self.sync_frame = QtWidgets.QFrame(self.frame)
        self.sync_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.sync_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sync_frame.setObjectName("sync_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sync_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.recent_news_icon_3 = QtWidgets.QToolButton(self.sync_frame)
        self.recent_news_icon_3.setText("")
        self.recent_news_icon_3.setIcon(icon10)
        self.recent_news_icon_3.setIconSize(QtCore.QSize(20, 20))
        self.recent_news_icon_3.setObjectName("recent_news_icon_3")
        self.horizontalLayout_3.addWidget(self.recent_news_icon_3)
        self.news_label_3 = QtWidgets.QLabel(self.sync_frame)
        self.news_label_3.setObjectName("news_label_3")
        self.horizontalLayout_3.addWidget(self.news_label_3)
        self.verticalLayout_4.addWidget(self.sync_frame)
        self.gridLayout_7.addWidget(self.frame, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.news_box)
        self.gridLayout_9.addWidget(self.welcome_box, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 0, 1, 1, 1)
        self.main_stackWidget.addWidget(self.welcome_page)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.main_stackWidget.addWidget(self.page_5)
        self.ContentGrid.addWidget(self.main_stackWidget, 0, 1, 1, 1)
        self.MainGrid.addLayout(self.ContentGrid, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.MainGrid, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_stackWidget.setCurrentIndex(0)
        self.project_stackWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vault"))
        self.profile_btn.setToolTip(_translate("MainWindow", "Profile"))
        self.notification_btn.setToolTip(_translate("MainWindow", "Notification"))
        self.sync_btn.setToolTip(_translate("MainWindow", "Sync"))
        self.preferrence_btn.setToolTip(_translate("MainWindow", "Preferrence"))
        self.log_off_btn.setToolTip(_translate("MainWindow", "Log Out"))
        self.project_btn.setToolTip(_translate("MainWindow", "Project"))
        self.project_btn.setText(_translate("MainWindow", " Project"))
        self.econom_btn.setToolTip(_translate("MainWindow", "Economy"))
        self.econom_btn.setText(_translate("MainWindow", "Economy"))
        self.member_btn.setToolTip(_translate("MainWindow", "Members"))
        self.member_btn.setText(_translate("MainWindow", " Members"))
        self.marketing_btn.setToolTip(_translate("MainWindow", "Marketing"))
        self.marketing_btn.setText(_translate("MainWindow", " Marketing"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.project_name_label.setText(_translate("MainWindow", "{{ Project name }}"))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_6.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_7.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_8.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_9.setText(_translate("MainWindow", "..."))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_10.setText(_translate("MainWindow", "..."))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_11.setText(_translate("MainWindow", "..."))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_12.setText(_translate("MainWindow", "..."))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.big_profile_btn.setToolTip(_translate("MainWindow", "{{name}} Profile"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome"))
        self.name_label.setToolTip(_translate("MainWindow", "Your are logged in as {{name}}"))
        self.name_label.setText(_translate("MainWindow", "{{name goes here}}"))
        self.news_label.setText(_translate("MainWindow", "TextLabel"))
        self.news_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.news_label_3.setText(_translate("MainWindow", "TextLabel"))

from UI import ui_resources

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

